# Culture Survey 2012 — SPSS Parsing & Exploration

This notebook loads and explores the **Kultura 2012** survey data from three Czech regions (Ústecký, Vysočina, Zlínský).

## Quick SPSS → Pandas Refresher

- **SPSS `.sav` files** store data + metadata (variable labels, value labels, missing value codes)
- **`pyreadstat`** reads `.sav` files and returns:
  - A pandas DataFrame (the actual data)
  - A metadata object (labels, creation info, etc.)
- Once loaded, you work with the DataFrame exactly like any pandas DataFrame

### Key concepts:
- **Variable labels**: Human-readable descriptions of columns (e.g., `Q1_1` → "How often do you visit libraries?")
- **Value labels**: Categorical codes mapped to text (e.g., `1` = "Never", `2` = "Once a month", `3` = "Weekly")
- **Missing values**: SPSS can define custom missing codes (e.g., `-99`, `999`) that pyreadstat converts to `NaN`

## 1. Setup — Load the Data

In [1]:
import pyreadstat
import pandas as pd
from pathlib import Path

In [2]:
# Path to the SPSS .sav file (relative to notebook location)
SPSS_FILE = Path("../data/culture_dataverse_files/Kult2012_3kraje_UstVysZli_CSDA_pub_nove_bez_jmen.sav")

# Read SPSS file — returns tuple: (DataFrame with data, metadata object with labels)
df, meta = pyreadstat.read_sav(SPSS_FILE)

# Print basic info: number of rows × columns
print(f"Loaded {df.shape[0]} rows × {df.shape[1]} columns")
# Print the file label from metadata (if any)
print(f"\nFile label: {meta.file_label or '(not set)'}")
# Print the table name from metadata
print(f"Table name: {meta.table_name}")
# Print the creation timestamp of the SPSS file
print(f"Created: {meta.creation_time}")

Loaded 3679 rows × 275 columns

File label: (not set)
Table name: None
Created: 2015-01-07 11:54:08

## 2. Explore Variable Labels

SPSS stores human-readable labels for each variable. Let's see what we're working with.

In [8]:
# All variable labels as a DataFrame for easy browsing
var_labels_df = pd.DataFrame({
    'variable': list(meta.column_names_to_labels.keys()),
    'label': list(meta.column_names_to_labels.values())
})

print(f"Total variables: {len(var_labels_df)}\n")
var_labels_df.head(20)

Total variables: 275

   variable                                              label
0        CD                                 CD Číslo dotazníku
1      KRAJ                                               Kraj
2       VER                         VER Verze dotazníku - kraj
3       KOD                                   KOD Číslo kodéra
4       SUP                          SUP Číslo superkontrolora
5       POR                               POR Číslo pořizovače
6      K.1a  K.1a Odkud čerpá informace o minulosti, tradic...
7      K.1b  K.1b Odkud čerpá informace o minulosti, tradic...
8      K.1c  K.1c Odkud čerpá informace o minulosti, tradic...
9       K.2  K.2 Vypráví, zprostředkovává ostatním minulost...
10      K.3  K.3 Jakou oblast měl na mysli v předchozích ot...
11      K.4               K.4 Zná krajově typické písně, tance
12      K.5                                K.5 Obec, kde bydlí
13      K.6                  K.6 Kde prožil dětství, dospívání
14      K.7  K.7 Kdy se přistěhoval do obce, města, kde žij...
15     K.8a      K.8a Žil v dospělosti převážně v KRAJI – otec
16     K.8b     K.8b Žil v dospělosti převážně v KRAJI – matka
17     K.8c  K.8c Žil v dospělosti převážně v KRAJI – prarodič
18     K.8d  K.8d Žil v dospělosti převážně v KRAJI – širší...
19      K.9                     K.9 Rád by se odstěhoval jinam

## 3. Explore Value Labels (Categorical Variables)

SPSS stores categories as numeric codes with text labels. Let's see which variables have them.

In [9]:
# Show all value label sets
print(f"Variables with value labels: {len(meta.value_labels)}\n")

# Pick a few examples to inspect
for var_name in list(meta.value_labels.keys())[:5]:
    print(f"\n{var_name}:")
    for code, label in meta.value_labels[var_name].items():
        print(f"  {code} → {label}")

Variables with value labels: 110


labels0:
  1.0 → Ústecký kraj
  2.0 → Kraj Vysočina
  3.0 → Zlínský kraj

labels1:
  1.0 → Ústecký kraj
  2.0 → Kraj Vysočina
  3.0 → Zlínský kraj

labels2:
  0.0 → BEZ ODPOVĚDI
  1.0 → Ze školy
  2.0 → Od rodinných příslušníků
  3.0 → Od známých a dalších pamětníků
  4.0 → Z návštěv výstav, muzeí, folklórních festivalů a podobných akcí
  5.0 → Z knih, dokumentů
  6.0 → Z internetu
  7.0 → Z médií (televize, rozhlas, noviny)
  8.0 → Odjinud
  98.0 → O HISTORII A TRADICE REGIONU SE NEZAJÍMÁ
  99.0 → NEVÍ

labels3:
  0.0 → BEZ ODPOVĚDI
  1.0 → velmi často
  2.0 → často
  3.0 → občas
  4.0 → zřídka
  5.0 → nikdy
  9.0 → NEVÍ

labels4:
  0.0 → BEZ ODPOVĚDI
  1.0 → zná, ale neumí
  2.0 → zná, umí je
  3.0 → zná, aktivně se věnuje
  4.0 → nezná žádné
  5.0 → nic takého u nich není
  9.0 → NEVÍ

## 4. Demographic Variables — First Look

Let's identify key demographic columns and their distributions.

In [10]:
# Common demographic variable patterns in this dataset
demo_vars = [v for v in df.columns if any(k in v.lower() for k in ['vek', 'pohl', 'vzdel', 'kraj', 'obec'])]

print("Potential demographic variables:")
for var in demo_vars:
    label = meta.column_names_to_labels.get(var, "(no label)")
    print(f"  {var}: {label}")

Potential demographic variables:
  KRAJ: Kraj
  t_vek_4: t_vek_4 - transformovaný věk - 4 kategorie
  kodkraj: Kód kraje
  nazevkraj: Název kraje
  pohlavi: Pohlaví
  vek: Věk
  vek6a: Věk 6 kat.
  vek4: Věk 4 kat. (kvóta)

In [11]:
# Show value counts for categorical variables with labels
def labeled_value_counts(series, var_name):
    """Print value counts with SPSS labels."""
    counts = series.value_counts().sort_index()
    
    # Get the value label set name for this variable
    label_set_name = meta.variable_to_label.get(var_name)
    labels = meta.value_labels.get(label_set_name, {}) if label_set_name else {}
    
    print(f"\n{var_name}: {meta.column_names_to_labels.get(var_name, '(no label)')}")
    print("-" * 50)
    for val, count in counts.items():
        label = labels.get(val, str(val)) if labels else str(val)
        print(f"  {val:>4} ({label:<20}): {count:>4} ({100*count/len(series):5.1f}%)")

# Example: check first few categorical variables
for var in list(meta.column_names_to_labels.keys())[:3]:
    labeled_value_counts(df[var], var)

CD: CD Číslo dotazníku
--------------------------------------------------
   1.0 (1.0                 ):    1 (  0.0%)
   2.0 (2.0                 ):    1 (  0.0%)
   3.0 (3.0                 ):    1 (  0.0%)
   4.0 (4.0                 ):    1 (  0.0%)
   5.0 (5.0                 ):    1 (  0.0%)
   6.0 (6.0                 ):    1 (  0.0%)
   7.0 (7.0                 ):    1 (  0.0%)
   8.0 (8.0                 ):    1 (  0.0%)
   9.0 (9.0                 ):    1 (  0.0%)
  10.0 (10.0                ):    1 (  0.0%)
  11.0 (11.0                ):    1 (  0.0%)
  12.0 (12.0                ):    1 (  0.0%)
  13.0 (13.0                ):    1 (  0.0%)
  14.0 (14.0                ):    1 (  0.0%)
  15.0 (15.0                ):    1 (  0.0%)
  16.0 (16.0                ):    1 (  0.0%)
  17.0 (17.0                ):    1 (  0.0%)
  18.0 (18.0                ):    1 (  0.0%)
  19.0 (19.0                ):    1 (  0.0%)
  20.0 (20.0                ):    1 (  0.0%)
  21.0 (21.0                ):    1 (  0.0%)
  22.0 (22.0                ):    1 (  0.0%)
  23.0 (23.0                ):    1 (  0.0%)
  24.0 (24.0                ):    1 (  0.0%)
  25.0 (25.0                ):    1 (  0.0%)
  26.0 (26.0                ):    1 (  0.0%)
  27.0 (27.0                ):    1 (  0.0%)
  28.0 (28.0                ):    1 (  0.0%)
  29.0 (29.0                ):    1 (  0.0%)
  30.0 (30.0                ):    1 (  0.0%)
  31.0 (31.0                ):    1 (  0.0%)
  32.0 (32.0                ):    1 (  0.0%)
  33.0 (33.0                ):    1 (  0.0%)
  34.0 (34.0                ):    1 (  0.0%)
  35.0 (35.0                ):    1 (  0.0%)
  36.0 (36.0                ):    1 (  0.0%)
  37.0 (37.0                ):    1 (  0.0%)
  38.0 (38.0                ):    1 (  0.0%)
  39.0 (39.0                ):    1 (  0.0%)
  40.0 (40.0                ):    1 (  0.0%)
  41.0 (41.0                ):    1 (  0.0%)
  42.0 (42.0                ):    1 (  0.0%)
  43.0 (43.0                ):    1 (  0.0%)
  44.0 (44.0                ):    1 (  0.0%)
  45.0 (45.0                ):    1 (  0.0%)
  46.0 (46.0                ):    1 (  0.0%)
  47.0 (47.0                ):    1 (  0.0%)
  48.0 (48.0                ):    1 (  0.0%)
  49.0 (49.0                ):    1 (  0.0%)
  50.0 (50.0                ):    1 (  0.0%)
  51.0 (51.0                ):    1 (  0.0%)
  52.0 (52.0                ):    1 (  0.0%)
  53.0 (53.0                ):    1 (  0.0%)
  54.0 (54.0                ):    1 (  0.0%)
  55.0 (55.0                ):    1 (  0.0%)
  56.0 (56.0                ):    1 (  0.0%)
  57.0 (57.0                ):    1 (  0.0%)
  58.0 (58.0                ):    1 (  0.0%)
  59.0 (59.0                ):    1 (  0.0%)
  60.0 (60.0                ):    1 (  0.0%)
  61.0 (61.0                ):    1 (  0.0%)
  62.0 (62.0                ):    1 (  0.0%)
  63.0 (63.0                ):    1 (  0.0%)
  64.0 (64.0                ):    1 (  0.0%)
  65.0 (65.0                ):    1 (  0.0%)
  66.0 (66.0                ):    1 (  0.0%)
  67.0 (67.0                ):    1 (  0.0%)
  68.0 (68.0                ):    1 (  0.0%)
  69.0 (69.0                ):    1 (  0.0%)
  70.0 (70.0                ):    1 (  0.0%)
  71.0 (71.0                ):    1 (  0.0%)
  72.0 (72.0                ):    1 (  0.0%)
  73.0 (73.0                ):    1 (  0.0%)
  74.0 (74.0                ):    1 (  0.0%)
  75.0 (75.0                ):    1 (  0.0%)
  76.0 (76.0                ):    1 (  0.0%)
  77.0 (77.0                ):    1 (  0.0%)
  78.0 (78.0                ):    1 (  0.0%)
  79.0 (79.0                ):    1 (  0.0%)
  80.0 (80.0                ):    1 (  0.0%)
  81.0 (81.0                ):    1 (  0.0%)
  82.0 (82.0                ):    1 (  0.0%)
  83.0 (83.0                ):    1 (  0.0%)
  84.0 (84.0                ):    1 (  0.0%)
  85.0 (85.0                ):    1 (  0.0%)
  86.0 (86.0                ):    1 (  0.0%)
  87.0 (87.0                ):    1 (  0.0%)
  88.0 (88.0                ):    1 (  0.0%)
  89.0 (89.0                ):    1 (  0.0%)
  90.0 (90.0                ):    1 (  0.0%)
  91.0 (91.0                ):    1 (  0.0%)
  92.0 (92.0                ):    1 (  0.0%)
  93.0 (93.0                ):    1 (  0.0%)
  94.0 (94.0                ):    1 (  0.0%)
  95.0 (95.0                ):    1 (  0.0%)
  96.0 (96.0                ):    1 (  0.0%)
  97.0 (97.0                ):    1 (  0.0%)
  98.0 (98.0                ):    1 (  0.0%)
  99.0 (99.0                ):    1 (  0.0%)
  100.0 (100.0               ):    1 (  0.0%)
  101.0 (101.0               ):    1 (  0.0%)
  102.0 (102.0               ):    1 (  0.0%)
  103.0 (103.0               ):    1 (  0.0%)
  104.0 (104.0               ):    1 (  0.0%)
  105.0 (105.0               ):    1 (  0.0%)
  106.0 (106.0               ):    1 (  0.0%)
  107.0 (107.0               ):    1 (  0.0%)
  108.0 (108.0               ):    1 (  0.0%)
  109.0 (109.0               ):    1 (  0.0%)
  110.0 (110.0               ):    1 (  0.0%)
  111.0 (111.0               ):    1 (  0.0%)
  112.0 (112.0               ):    1 (  0.0%)
  113.0 (113.0               ):    1 (  0.0%)
  114.0 (114.0               ):    1 (  0.0%)
  115.0 (115.0               ):    1 (  0.0%)
  116.0 (116.0               ):    1 (  0.0%)
  117.0 (117.0               ):    1 (  0.0%)
  118.0 (118.0               ):    1 (  0.0%)
  119.0 (119.0               ):    1 (  0.0%)
  120.0 (120.0               ):    1 (  0.0%)
  121.0 (121.0               ):    1 (  0.0%)
  122.0 (122.0               ):    1 (  0.0%)
  123.0 (123.0               ):    1 (  0.0%)
  124.0 (124.0               ):    1 (  0.0%)
  125.0 (125.0               ):    1 (  0.0%)
  126.0 (126.0               ):    1 (  0.0%)
  127.0 (127.0               ):    1 (  0.0%)
  128.0 (128.0               ):    1 (  0.0%)
  129.0 (129.0               ):    1 (  0.0%)
  130.0 (130.0               ):    1 (  0.0%)
  131.0 (131.0               ):    1 (  0.0%)
  132.0 (132.0               ):    1 (  0.0%)
  133.0 (133.0               ):    1 (  0.0%)
  134.0 (134.0               ):    1 (  0.0%)
  135.0 (135.0               ):    1 (  0.0%)
  136.0 (136.0               ):    1 (  0.0%)
  137.0 (137.0               ):    1 (  0.0%)
  138.0 (138.0               ):    1 (  0.0%)
  139.0 (139.0               ):    1 (  0.0%)
  140.0 (140.0               ):    1 (  0.0%)
  141.0 (141.0               ):    1 (  0.0%)
  142.0 (142.0               ):    1 (  0.0%)
  143.0 (143.0               ):    1 (  0.0%)
  144.0 (144.0               ):    1 (  0.0%)
  145.0 (145.0               ):    1 (  0.0%)
  146.0 (146.0               ):    1 (  0.0%)
  147.0 (147.0               ):    1 (  0.0%)
  148.0 (148.0               ):    1 (  0.0%)
  149.0 (149.0               ):    1 (  0.0%)
  150.0 (150.0               ):    1 (  0.0%)
  151.0 (151.0               ):    1 (  0.0%)
  152.0 (152.0               ):    1 (  0.0%)
  153.0 (153.0               ):    1 (  0.0%)
  154.0 (154.0               ):    1 (  0.0%)
  155.0 (155.0               ):    1 (  0.0%)
  156.0 (156.0               ):    1 (  0.0%)
  157.0 (157.0               ):    1 (  0.0%)
  158.0 (158.0               ):    1 (  0.0%)
  159.0 (159.0               ):    1 (  0.0%)
  160.0 (160.0               ):    1 (  0.0%)
  161.0 (161.0               ):    1 (  0.0%)
  162.0 (162.0               ):    1 (  0.0%)
  163.0 (163.0               ):    1 (  0.0%)
  164.0 (164.0               ):    1 (  0.0%)
  165.0 (165.0               ):    1 (  0.0%)
  166.0 (166.0               ):    1 (  0.0%)
  167.0 (167.0               ):    1 (  0.0%)
  168.0 (168.0               ):    1 (  0.0%)
  169.0 (169.0               ):    1 (  0.0%)
  170.0 (170.0               ):    1 (  0.0%)
  171.0 (171.0               ):    1 (  0.0%)
  172.0 (172.0               ):    1 (  0.0%)
  173.0 (173.0               ):    1 (  0.0%)
  174.0 (174.0               ):    1 (  0.0%)
  175.0 (175.0               ):    1 (  0.0%)
  176.0 (176.0               ):    1 (  0.0%)
  177.0 (177.0               ):    1 (  0.0%)
  178.0 (178.0               ):    1 (  0.0%)
  179.0 (179.0               ):    1 (  0.0%)
  180.0 (180.0               ):    1 (  0.0%)
  181.0 (181.0               ):    1 (  0.0%)
  182.0 (182.0               ):    1 (  0.0%)
  183.0 (183.0               ):    1 (  0.0%)
  184.0 (184.0               ):    1 (  0.0%)
  185.0 (185.0               ):    1 (  0.0%)
  186.0 (186.0               ):    1 (  0.0%)
  187.0 (187.0               ):    1 (  0.0%)
  188.0 (188.0               ):    1 (  0.0%)
  189.0 (189.0               ):    1 (  0.0%)
  190.0 (190.0               ):    1 (  0.0%)
  191.0 (191.0               ):    1 (  0.0%)
  192.0 (192.0               ):    1 (  0.0%)
  193.0 (193.0               ):    1 (  0.0%)
  194.0 (194.0               ):    1 (  0.0%)
  195.0 (195.0               ):    1 (  0.0%)
  196.0 (196.0               ):    1 (  0.0%)
  197.0 (197.0               ):    1 (  0.0%)
  198.0 (198.0               ):    1 (  0.0%)
  199.0 (199.0               ):    1 (  0.0%)
  200.0 (200.0               ):    1 (  0.0%)
  201.0 (201.0               ):    1 (  0.0%)
  202.0 (202.0               ):    1 (  0.0%)
  203.0 (203.0               ):    1 (  0.0%)
  204.0 (204.0               ):    1 (  0.0%)
  205.0 (205.0               ):    1 (  0.0%)
  206.0 (206.0               ):    1 (  0.0%)
  207.0 (207.0               ):    1 (  0.0%)
  208.0 (208.0               ):    1 (  0.0%)
  209.0 (209.0               ):    1 (  0.0%)
  210.0 (210.0               ):    1 (  0.0%)
  211.0 (211.0               ):    1 (  0.0%)
  212.0 (212.0               ):    1 (  0.0%)
  213.0 (213.0               ):    1 (  0.0%)
  214.0 (214.0               ):    1 (  0.0%)
  215.0 (215.0               ):    1 (  0.0%)
  216.0 (216.0               ):    1 (  0.0%)
  217.0 (217.0               ):    1 (  0.0%)
  218.0 (218.0               ):    1 (  0.0%)
  219.0 (219.0               ):    1 (  0.0%)
  220.0 (220.0               ):    1 (  0.0%)
  221.0 (221.0               ):    1 (  0.0%)
  222.0 (222.0               ):    1 (  0.0%)
  223.0 (223.0               ):    1 (  0.0%)
  224.0 (224.0               ):    1 (  0.0%)
  225.0 (225.0               ):    1 (  0.0%)
  226.0 (226.0               ):    1 (  0.0%)
  227.0 (227.0               ):    1 (  0.0%)
  228.0 (228.0               ):    1 (  0.0%)
  229.0 (229.0               ):    1 (  0.0%)
  230.0 (230.0               ):    1 (  0.0%)
  231.0 (231.0               ):    1 (  0.0%)
  232.0 (232.0               ):    1 (  0.0%)
  233.0 (233.0               ):    1 (  0.0%)
  234.0 (234.0               ):    1 (  0.0%)
  235.0 (235.0               ):    1 (  0.0%)
  236.0 (236.0               ):    1 (  0.0%)
  237.0 (237.0               ):    1 (  0.0%)
  238.0 (238.0               ):    1 (  0.0%)
  239.0 (239.0               ):    1 (  0.0%)
  240.0 (240.0               ):    1 (  0.0%)
  241.0 (241.0               ):    1 (  0.0%)
  242.0 (242.0               ):    1 (  0.0%)
  243.0 (243.0               ):    1 (  0.0%)
  244.0 (244.0               ):    1 (  0.0%)
  245.0 (245.0               ):    1 (  0.0%)
  246.0 (246.0               ):    1 (  0.0%)
  247.0 (247.0               ):    1 (  0.0%)
  248.0 (248.0               ):    1 (  0.0%)
  249.0 (249.0               ):    1 (  0.0%)
  250.0 (250.0               ):    1 (  0.0%)
  251.0 (251.0               ):    1 (  0.0%)
  252.0 (252.0               ):    1 (  0.0%)
  253.0 (253.0               ):    1 (  0.0%)
  254.0 (254.0               ):    1 (  0.0%)
  255.0 (255.0               ):    1 (  0.0%)
  256.0 (256.0               ):    1 (  0.0%)
  257.0 (257.0               ):    1 (  0.0%)
  258.0 (258.0               ):    1 (  0.0%)
  259.0 (259.0               ):    1 (  0.0%)
  260.0 (260.0               ):    1 (  0.0%)
  261.0 (261.0               ):    1 (  0.0%)
  262.0 (262.0               ):    1 (  0.0%)
  263.0 (263.0               ):    1 (  0.0%)
  264.0 (264.0               ):    1 (  0.0%)
  265.0 (265.0               ):    1 (  0.0%)
  266.0 (266.0               ):    1 (  0.0%)
  267.0 (267.0               ):    1 (  0.0%)
  268.0 (268.0               ):    1 (  0.0%)
  269.0 (269.0               ):    1 (  0.0%)
  270.0 (270.0               ):    1 (  0.0%)
  271.0 (271.0               ):    1 (  0.0%)
  272.0 (272.0               ):    1 (  0.0%)
  273.0 (273.0               ):    1 (  0.0%)
  274.0 (274.0               ):    1 (  0.0%)
  275.0 (275.0               ):    1 (  0.0%)
  276.0 (276.0               ):    1 (  0.0%)
  277.0 (277.0               ):    1 (  0.0%)
  278.0 (278.0               ):    1 (  0.0%)
  279.0 (279.0               ):    1 (  0.0%)
  280.0 (280.0               ):    1 (  0.0%)
  281.0 (281.0               ):    1 (  0.0%)
  282.0 (282.0               ):    1 (  0.0%)
  283.0 (283.0               ):    1 (  0.0%)
  284.0 (284.0               ):    1 (  0.0%)
  285.0 (285.0               ):    1 (  0.0%)
  286.0 (286.0               ):    1 (  0.0%)
  287.0 (287.0               ):    1 (  0.0%)
  288.0 (288.0               ):    1 (  0.0%)
  289.0 (289.0               ):    1 (  0.0%)
  290.0 (290.0               ):    1 (  0.0%)
  291.0 (291.0               ):    1 (  0.0%)
  292.0 (292.0               ):    1 (  0.0%)
  293.0 (293.0               ):    1 (  0.0%)
  294.0 (294.0               ):    1 (  0.0%)
  295.0 (295.0               ):    1 (  0.0%)
  296.0 (296.0               ):    1 (  0.0%)
  297.0 (297.0               ):    1 (  0.0%)
  298.0 (298.0               ):    1 (  0.0%)
  299.0 (299.0               ):    1 (  0.0%)
  300.0 (300.0               ):    1 (  0.0%)
  301.0 (301.0               ):    1 (  0.0%)
  302.0 (302.0               ):    1 (  0.0%)
  303.0 (303.0               ):    1 (  0.0%)
  304.0 (304.0               ):    1 (  0.0%)
  305.0 (305.0               ):    1 (  0.0%)
  306.0 (306.0               ):    1 (  0.0%)
  307.0 (307.0               ):    1 (  0.0%)
  308.0 (308.0               ):    1 (  0.0%)
  309.0 (309.0               ):    1 (  0.0%)
  310.0 (310.0               ):    1 (  0.0%)
  311.0 (311.0               ):    1 (  0.0%)
  312.0 (312.0               ):    1 (  0.0%)
  313.0 (313.0               ):    1 (  0.0%)
  314.0 (314.0               ):    1 (  0.0%)
  315.0 (315.0               ):    1 (  0.0%)
  316.0 (316.0               ):    1 (  0.0%)
  317.0 (317.0               ):    1 (  0.0%)
  318.0 (318.0               ):    1 (  0.0%)
  319.0 (319.0               ):    1 (  0.0%)
  320.0 (320.0               ):    1 (  0.0%)
  321.0 (321.0               ):    1 (  0.0%)
  322.0 (322.0               ):    1 (  0.0%)
  323.0 (323.0               ):    1 (  0.0%)
  324.0 (324.0               ):    1 (  0.0%)
  325.0 (325.0               ):    1 (  0.0%)
  326.0 (326.0               ):    1 (  0.0%)
  327.0 (327.0               ):    1 (  0.0%)
  328.0 (328.0               ):    1 (  0.0%)
  329.0 (329.0               ):    1 (  0.0%)
  330.0 (330.0               ):    1 (  0.0%)
  331.0 (331.0               ):    1 (  0.0%)
  332.0 (332.0               ):    1 (  0.0%)
  333.0 (333.0               ):    1 (  0.0%)
  334.0 (334.0               ):    1 (  0.0%)
  335.0 (335.0               ):    1 (  0.0%)
  336.0 (336.0               ):    1 (  0.0%)
  337.0 (337.0               ):    1 (  0.0%)
  338.0 (338.0               ):    1 (  0.0%)
  339.0 (339.0               ):    1 (  0.0%)
  340.0 (340.0               ):    1 (  0.0%)
  341.0 (341.0               ):    1 (  0.0%)
  342.0 (342.0               ):    1 (  0.0%)
  343.0 (343.0               ):    1 (  0.0%)
  344.0 (344.0               ):    1 (  0.0%)
  345.0 (345.0               ):    1 (  0.0%)
  346.0 (346.0               ):    1 (  0.0%)
  347.0 (347.0               ):    1 (  0.0%)
  348.0 (348.0               ):    1 (  0.0%)
  349.0 (349.0               ):    1 (  0.0%)
  350.0 (350.0               ):    1 (  0.0%)
  351.0 (351.0               ):    1 (  0.0%)
  352.0 (352.0               ):    1 (  0.0%)
  353.0 (353.0               ):    1 (  0.0%)
  354.0 (354.0               ):    1 (  0.0%)
  355.0 (355.0               ):    1 (  0.0%)
  356.0 (356.0               ):    1 (  0.0%)
  357.0 (357.0               ):    1 (  0.0%)
  358.0 (358.0               ):    1 (  0.0%)
  359.0 (359.0               ):    1 (  0.0%)
  360.0 (360.0               ):    1 (  0.0%)
  361.0 (361.0               ):    1 (  0.0%)
  362.0 (362.0               ):    1 (  0.0%)
  363.0 (363.0               ):    1 (  0.0%)
  364.0 (364.0               ):    1 (  0.0%)
  365.0 (365.0               ):    1 (  0.0%)
  366.0 (366.0               ):    1 (  0.0%)
  367.0 (367.0               ):    1 (  0.0%)
  368.0 (368.0               ):    1 (  0.0%)
  369.0 (369.0               ):    1 (  0.0%)
  370.0 (370.0               ):    1 (  0.0%)
  371.0 (371.0               ):    1 (  0.0%)
  372.0 (372.0               ):    1 (  0.0%)
  373.0 (373.0               ):    1 (  0.0%)
  374.0 (374.0               ):    1 (  0.0%)
  375.0 (375.0               ):    1 (  0.0%)
  376.0 (376.0               ):    1 (  0.0%)
  377.0 (377.0               ):    1 (  0.0%)
  378.0 (378.0               ):    1 (  0.0%)
  379.0 (379.0               ):    1 (  0.0%)
  380.0 (380.0               ):    1 (  0.0%)
  381.0 (381.0               ):    1 (  0.0%)
  382.0 (382.0               ):    1 (  0.0%)
  383.0 (383.0               ):    1 (  0.0%)
  384.0 (384.0               ):    1 (  0.0%)
  385.0 (385.0               ):    1 (  0.0%)
  386.0 (386.0               ):    1 (  0.0%)
  387.0 (387.0               ):    1 (  0.0%)
  388.0 (388.0               ):    1 (  0.0%)
  389.0 (389.0               ):    1 (  0.0%)
  390.0 (390.0               ):    1 (  0.0%)
  391.0 (391.0               ):    1 (  0.0%)
  392.0 (392.0               ):    1 (  0.0%)
  393.0 (393.0               ):    1 (  0.0%)
  394.0 (394.0               ):    1 (  0.0%)
  395.0 (395.0               ):    1 (  0.0%)
  396.0 (396.0               ):    1 (  0.0%)
  397.0 (397.0               ):    1 (  0.0%)
  398.0 (398.0               ):    1 (  0.0%)
  399.0 (399.0               ):    1 (  0.0%)
  400.0 (400.0               ):    1 (  0.0%)
  401.0 (401.0               ):    1 (  0.0%)
  402.0 (402.0               ):    1 (  0.0%)
  403.0 (403.0               ):    1 (  0.0%)
  404.0 (404.0               ):    1 (  0.0%)
  405.0 (405.0               ):    1 (  0.0%)
  406.0 (406.0               ):    1 (  0.0%)
  407.0 (407.0               ):    1 (  0.0%)
  408.0 (408.0               ):    1 (  0.0%)
  409.0 (409.0               ):    1 (  0.0%)
  410.0 (410.0               ):    1 (  0.0%)
  411.0 (411.0               ):    1 (  0.0%)
  412.0 (412.0               ):    1 (  0.0%)
  413.0 (413.0               ):    1 (  0.0%)
  414.0 (414.0               ):    1 (  0.0%)
  415.0 (415.0               ):    1 (  0.0%)
  416.0 (416.0               ):    1 (  0.0%)
  417.0 (417.0               ):    1 (  0.0%)
  418.0 (418.0               ):    1 (  0.0%)
  419.0 (419.0               ):    1 (  0.0%)
  420.0 (420.0               ):    1 (  0.0%)
  421.0 (421.0               ):    1 (  0.0%)
  422.0 (422.0               ):    1 (  0.0%)
  423.0 (423.0               ):    1 (  0.0%)
  424.0 (424.0               ):    1 (  0.0%)
  425.0 (425.0               ):    1 (  0.0%)
  426.0 (426.0               ):    1 (  0.0%)
  427.0 (427.0               ):    1 (  0.0%)
  428.0 (428.0               ):    1 (  0.0%)
  429.0 (429.0               ):    1 (  0.0%)
  430.0 (430.0               ):    1 (  0.0%)
  431.0 (431.0               ):    1 (  0.0%)
  432.0 (432.0               ):    1 (  0.0%)
  433.0 (433.0               ):    1 (  0.0%)
  434.0 (434.0               ):    1 (  0.0%)
  435.0 (435.0               ):    1 (  0.0%)

## 5. Missing Values

SPSS often defines custom missing codes. pyreadstat converts these to `NaN` by default.

In [12]:
# Missing value summary
missing_summary = df.isna().sum().sort_values(ascending=False)
missing_pct = 100 * missing_summary / len(df)

print("Top 15 variables by missing values:\n")
result = pd.DataFrame({'missing_count': missing_summary.head(15), 'missing_pct': missing_pct.head(15)})
result[result['missing_count'] > 0]

Top 15 variables by missing values:

        missing_count  missing_pct
xxxxx1           3679   100.000000
K.79c            3537    96.140256
K.18b            3293    89.508018
K.79b            3034    82.468062
K.20             3021    82.114705
K.19             3016    81.978799
K.79a            2515    68.360968
K.7              2427    65.969013
K.81             2049    55.694482
K.71             1956    53.166621
K.32c            1890    51.372656
K.82             1836    49.904865
K.15k            1707    46.398478
K.32b            1453    39.494428
K.47             1431    38.896439

## 6. Optional: Apply Value Labels Automatically

Convert coded values to their text labels for easier exploration.

In [13]:
# Re-read with value labels applied as strings
df_labeled, _ = pyreadstat.read_sav(SPSS_FILE, apply_value_formats=True)

# Compare: original vs labeled
print("Original (coded):")
print(df.iloc[:3, :5])

print("\nLabeled (text values):")
print(df_labeled.iloc[:3, :5])

Original (coded):
       CD  KRAJ  VER   KOD   SUP
0  1158.0   1.0  1.0  13.0  11.0
1  1159.0   1.0  1.0  13.0  11.0
2  1160.0   1.0  1.0  13.0  11.0

Labeled (text values):
       CD          KRAJ           VER   KOD   SUP
0  1158.0  Ústecký kraj  Ústecký kraj  13.0  11.0
1  1159.0  Ústecký kraj  Ústecký kraj  13.0  11.0
2  1160.0  Ústecký kraj  Ústecký kraj  13.0  11.0

In [14]:
df_labeled.head(5)

,CD,KRAJ,VER,KOD,SUP,POR,K.1a,K.1b,K.1c,K.2,...,velobce3b,pohlavi,t_vzd,vek,vek6a,vek4,prijemDom17k,prijemDom3ter,k71vstupenky,k72knihyCD
0,1158.0,Ústecký kraj,Ústecký kraj,13.0,11.0,11.0,"Z médií (televize, rozhlas, noviny)",NaN,NaN,zřídka,...,do 2 tis.,žena,střední bez maturity,57.0,46-59,45-62,27001 - 29000,II. tercil,100.0,0.0
1,1159.0,Ústecký kraj,Ústecký kraj,13.0,11.0,11.0,Od známých a dalších pamětníků,Z internetu,"Z knih, dokumentů",zřídka,...,do 2 tis.,žena,střední bez maturity,38.0,36-45,30-44,29001 - 30000,II. tercil,300.0,0.0
2,1160.0,Ústecký kraj,Ústecký kraj,13.0,11.0,11.0,Ze školy,Z internetu,"Z médií (televize, rozhlas, noviny)",nikdy,...,do 2 tis.,žena,střední s maturitou,21.0,20-26,20-29,29001 - 30000,II. tercil,600.0,50.0
3,1249.0,Ústecký kraj,Ústecký kraj,8.0,2.0,2.0,Z internetu,Od známých a dalších pamětníků,"Z knih, dokumentů",zřídka,...,do 2 tis.,muž,střední bez maturity,49.0,46-59,45-62,36001 - 40000,III. tercil,1500.0,0.0
4,1251.0,Ústecký kraj,Ústecký kraj,8.0,2.0,2.0,"Z knih, dokumentů",Od známých a dalších pamětníků,NaN,občas,...,do 2 tis.,žena,střední bez maturity,60.0,60-69,45-62,29001 - 30000,II. tercil,1200.0,200.0

## Next Steps

- Identify specific research questions (e.g., cultural participation by region/education)
- Cross-tabulate variables using `pd.crosstab()`
- Group by region (`KRAJ`) and compare responses
- Export cleaned data to CSV/Parquet for further analysis